
on: 
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Name of Resource Group'
        default: 'arav-rg-aue-nsgcsv'
        required: true
      subscriptionId:
        description: 'Provide Subscription ID'
        default: '3d3c613c-3828-4c8d-bc51-8871f888c18e'
        required: true
      deployBicep:
        description: 'Flag to deploy via Bicep'
        default: 'Yes'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
         creds: ${{secrets.AZURE_CREDENTIALS}}
         enable-AzPSSession: true
   
      - name: NSG Preprocessing 
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            .\Scripts\NSGPreprocessing.ps1 -ParamJsonPath '.\Parameters\' -Paramfilename 'nsgs-aue.parameters.json'  -GlobalNSGPath '.\Parameters\GlobalNSG.csv' -SubscriptionNSGPath '.\Parameters\subscriptionNSG.csv' -rgname 'arav-rg-aue-nsgcsv'
          azPSVersion: latest
          errorActionPreference: stop 
          failOnStandardError: true 

